services:
  - type: web
    name: backend
    env: node
    buildCommand: cd ../.. && pnpm install && pnpm build --filter=@repo/backend
    startCommand: cd apps/backend && node ./dist/index.js
    envVars:
      - key: NODE_ENV
        value: production 